# Generated by Django 2.1 on 2018-08-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DBConnections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MissingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('extension', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('sqlquery', 'Consulta SQL'), ('item', 'Objetos Perdidos'), ('directory', 'Directorio de Dependencias'), ('localization', 'Geolocalizacion de Bloques')], max_length=20)),
                ('permits', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SQLQuery',
            fields=[
                ('Service', models.OneToOneField(limit_choices_to={'kind': 'sqlquery'}, on_delete='CASCADE', primary_key=True, related_name='query', related_query_name='query', serialize=False, to='Services.Service')),
                ('query', models.TextField(max_length=200)),
                ('pilot', models.ImageField(upload_to='photos')),
                ('Connection', models.ForeignKey(on_delete='PROTECTED', to='DBConnections.Connection')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='Service',
            field=models.ForeignKey(limit_choices_to={'kind': 'directory'}, on_delete='CASCADE', related_name='offices', related_query_name='office', to='Services.Service'),
        ),
        migrations.AddField(
            model_name='missingitem',
            name='Service',
            field=models.ForeignKey(limit_choices_to={'kind': 'item'}, on_delete='CASCADE', related_name='items', related_query_name='item', to='Services.Service'),
        ),
        migrations.AddField(
            model_name='location',
            name='Service',
            field=models.ForeignKey(limit_choices_to={'kind': 'localization'}, on_delete='CASCADE', related_name='locations', related_query_name='location', to='Services.Service'),
        ),
    ]
