# Generated by Django 2.1 on 2018-10-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sqlquery',
            name='Connection',
        ),
        migrations.RemoveField(
            model_name='sqlquery',
            name='pilot',
        ),
    ]
