# Generated by Django 2.1 on 2018-10-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_auto_20181029_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingitem',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
