# Generated by Django 2.1 on 2018-08-14 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('motto', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='photos')),
                ('mission', models.TextField(max_length=500)),
                ('vision', models.TextField(max_length=500)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
    ]
